name: publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - uses: denoland/setup-deno@v1
      with:
        deno-version: canary

    - name: Run build script
      run: deno run -A tasks/build_npm.ts ${{ $GITHUB_SHA }}

    - name: Create temporary directory
      run: mkdir ~/temp

    - name: Copy contents of npm/ to temp directory
      run: cp -r npm/* ~/temp/

    - name: Check if npm branch exists
      run: |
        # Check if the npm branch exists
        # If it doesn't exist, create it
        git rev-parse --verify npm || \
        git checkout -b npm

    - name: Remove all files and directories in the npm branch
      run: rm -rf *

    - name: Copy contents of temp to the npm branch
      run: cp -r ~/temp/* .

    - name: Check for changes on npm branch
      run: git diff --exit-code HEAD

    - name: Deploy to npm branch
      # If the previous step succeeded (i.e., there are changes), deploy to npm branch
      if: success()
      run: |
        # Stage the changes, commit, and push
        git add . && \
        git commit -m "Publish build output" && \
        git push origin npm
